version: "3.7"
services: 
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  postgres:
    ports:
      - "5432:5432"
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=developer
      - POSTGRES_DB=sms_queue
    volumes:
      - postgres:/var/lib/postgresql/data
  webapp:
    build: .
    volumes:
      - .:/app
    ports:
    - "9292:9292"
    env_file: .env
    environment:
    - DATABASE_HOST=postgres
    - REDIS_HOST=redis
    depends_on:
    - postgres
    - redis
volumes:
  postgres: {}
  redis: {}